-- Dummy intake submissions for testing the admin panel
-- Run the migration first: ALTER TABLE public.intake_submissions ADD COLUMN company_name text;
-- Then paste this into the Supabase SQL editor and run

INSERT INTO public.intake_submissions (
  name, email, title, stakeholders,
  company_name, project_name, phases, pitch, excitement, key_feature, vision, avoid, audience, challenge, competitors,
  video_links,
  deliverables, deliverable_notes,
  timeline, timeline_date, timeline_notes,
  priority_order,
  experience, experience_notes,
  partners, partner_details,
  public_goal, internal_goal,
  budget, email_list_size,
  file_urls,
  anything_else, referral,
  status, created_at
) VALUES

-- 1. Crowdfunding campaign — full fields
(
  'Maya Chen', 'maya@luminboard.com', 'CEO & Co-Founder',
  E'Jordan <jordan@luminboard.com> \u2014 CTO\nPriya <priya@luminboard.com> \u2014 Head of Marketing',
  'LuminBoard Inc.', 'LuminBoard', ARRAY['build', 'launch', 'crowdfunding'],
  'A smart LED panel that syncs with your music and doubles as wall art.',
  'We want people to feel the energy of a live show in their living room.',
  'The real-time audio-reactive mode — nothing else on the market does this.',
  'A cinematic hero video that makes you FEEL the product, plus short social cuts for ads.',
  'Generic tech-bro vibes. We want warmth and creativity, not cold minimalism.',
  'Music lovers 25-40, apartment dwellers, design-conscious millennials.',
  'People think it''s just another LED strip. We need to show the art side.',
  'Nanoleaf, LIFX, Govee',
  E'https://vimeo.com/123456 \u2014 love the pacing and color grading\nhttps://youtube.com/watch?v=dQw4w9WgXcQ \u2014 the storytelling here is chef''s kiss',
  ARRAY['flagship', 'social_cuts', 'photography_lifestyle', 'photography_product', 'ads', 'landing_page'],
  'We need 15s, 30s, and 60s social cuts for Meta and TikTok.',
  'specific', '2026-05-15', 'Kickstarter launch is May 20th — need everything by the 15th.',
  ARRAY['quality', 'speed', 'cost'],
  'some', 'We did a DIY product video last year but it looked amateur.',
  ARRAY['photographer', 'copywriter'], 'Our photographer is Sarah Kim (@sarahkimphoto)',
  '$50,000', '$75,000',
  '$15,000 - $25,000', '500-1000',
  ARRAY[]::text[],
  'We have a prototype unit we can ship to your studio.', 'Found you through the Kickstarter Creator community on Reddit',
  'new', now() - interval '2 hours'
),

-- 2. Fundraising pitch — investor-focused
(
  'David Park', 'david@hearthhealth.ai', 'Founder', NULL,
  'Hearth Health AI', 'Hearth Health', ARRAY['fundraising'],
  'AI-powered cardiac monitoring that catches issues 48 hours before traditional methods.',
  'The potential to literally save lives with earlier detection.',
  'Our proprietary algorithm that predicts cardiac events with 94% accuracy.',
  'A 2-minute pitch video that makes VCs understand the massive TAM and our unfair advantage.',
  'Don''t make it feel like a pharma ad. We want Silicon Valley energy with medical credibility.',
  'Series A investors, health-tech focused VCs, strategic partners in cardiology.',
  'Explaining AI accuracy without sounding like vaporware.',
  'AliveCor, Withings, Apple Watch heart features',
  NULL,
  ARRAY['pitch_video', 'motion_graphics'],
  'Need animated data visualizations showing our accuracy vs competitors.',
  'soon', NULL, 'Raising in Q2, want to have materials ready.',
  ARRAY['quality', 'cost', 'speed'],
  'experienced', 'We worked with a Bay Area production company for our seed round video.',
  ARRAY[]::text[], NULL,
  NULL, NULL,
  '$10,000 - $15,000', NULL,
  ARRAY[]::text[],
  'Happy to share our deck under NDA. We have FDA breakthrough device designation.', NULL,
  'new', now() - interval '1 day'
),

-- 3. Scale partnership — ongoing content
(
  'Rachel Torres', 'rachel@wavecollective.co', 'Marketing Director',
  E'Alex <alex@wavecollective.co> \u2014 Brand Manager\nSam <sam@wavecollective.co> \u2014 Social Media Lead',
  'Wave Collective', 'Wave Collective', ARRAY['scale'],
  'Sustainable swimwear made from recycled ocean plastic. B-Corp certified.',
  'Every suit pulls 2 lbs of plastic from the ocean. The impact story is incredible.',
  'The ocean-to-swimwear transformation process — it''s visually stunning.',
  'Monthly content drops: 2 hero videos + 8 social cuts per month, seasonal campaigns.',
  'Greenwashing vibes. We have real certifications — let the facts speak.',
  'Eco-conscious women 22-35, coastal lifestyle, fitness-oriented.',
  'Standing out in a crowded sustainable fashion space.',
  'Girlfriend Collective, Patagonia, Summersalt',
  'https://vimeo.com/789012 — this brand film energy is exactly what we want',
  ARRAY['flagship', 'social_cuts', 'photography_lifestyle', 'testimonials', 'gifs', 'brand_story'],
  'We need a content calendar approach — consistent monthly output.',
  'later', NULL, 'Looking to start in Q3 and run through end of year.',
  ARRAY['cost', 'quality', 'speed'],
  'experienced', 'We''ve worked with 3 video agencies over the past 2 years. Looking for a long-term partner.',
  ARRAY['photographer', 'models', 'stylist'], 'We have a roster of models and a stylist on retainer.',
  NULL, NULL,
  '$5,000 - $10,000', NULL,
  ARRAY[]::text[],
  'Open to a retainer model if the pricing makes sense.', 'Jasmine from Tidal Branding recommended you',
  'reviewed', now() - interval '3 days'
),

-- 4. Build only — brand new startup
(
  'Tommy Nguyen', 'tommy@pegasusrobotics.io', 'Co-Founder', NULL,
  'Pegasus Robotics', 'Pegasus Robotics', ARRAY['build'],
  'Autonomous delivery drones for last-mile logistics in suburban neighborhoods.',
  'Watching a drone deliver a package to someone''s backyard for the first time.',
  'Our noise reduction tech — our drones are 10x quieter than competitors.',
  'Brand identity, messaging framework, and a content strategy before we shoot anything.',
  'Military/surveillance aesthetics. These are friendly neighborhood helpers.',
  'Suburban families, local businesses, municipal governments.',
  'Drone delivery has a PR problem. People think of invasion of privacy.',
  'Wing (Google), Amazon Prime Air, Zipline',
  NULL,
  ARRAY['scripting', 'brand_story'],
  'We need the strategy and scripting first, then we''ll come back for production.',
  'later', NULL, 'No rush — want to get the foundation right.',
  ARRAY['quality', 'speed', 'cost'],
  'none', NULL,
  ARRAY[]::text[], NULL,
  NULL, NULL,
  '$5,000 - $10,000', NULL,
  ARRAY[]::text[],
  NULL, NULL,
  'new', now() - interval '5 days'
),

-- 5. Build + Launch — standard project
(
  'Sofia Martinez', 'sofia@casaverde.mx', 'Brand Director',
  E'Carlos <carlos@casaverde.mx> \u2014 CEO\nElena <elena@casaverde.mx> \u2014 Operations',
  'Casa Verde', 'Casa Verde Mezcal', ARRAY['build', 'launch'],
  'Small-batch artisanal mezcal from Oaxaca, supporting indigenous farming communities.',
  'The craft and heritage behind every bottle. Generations of knowledge in each sip.',
  'Our direct-trade model — every purchase funds regenerative farming.',
  'A hero brand film + social content that captures the spirit of Oaxaca and our makers.',
  'Don''t exoticize or romanticize poverty. Show the dignity and expertise of our producers.',
  'Spirits enthusiasts 28-45, farm-to-table foodies, conscious consumers.',
  'Mezcal is trendy but people don''t understand the difference between artisanal and industrial.',
  'Del Maguey, Montelobos, Ilegal Mezcal',
  'https://youtube.com/watch?v=dQw4w9WgXcQ — love how they show the people behind the product',
  ARRAY['flagship', 'social_cuts', 'photography_lifestyle', 'photography_product', 'testimonials', 'brand_story'],
  'Need both English and Spanish versions of the hero video.',
  'asap', NULL, 'Trade show in 6 weeks — need hero video by then at minimum.',
  ARRAY['speed', 'quality', 'cost'],
  'some', 'Had a local videographer shoot some content but need professional quality.',
  ARRAY['copywriter', 'translator'], 'We need English-Spanish translation for all deliverables.',
  NULL, NULL,
  '$15,000 - $25,000', NULL,
  ARRAY[]::text[],
  'We can arrange a shoot trip to Oaxaca and cover travel + accommodation.', 'Met you at the Fancy Food Show booth',
  'new', now() - interval '12 hours'
);
