import {
  PricingTier,
  AddOn,
  CrowdfundingTier,
  FundraisingPackage,
} from '@/types/pricing';

export const pricingTiers: PricingTier[] = [
  {
    id: 'build',
    name: 'Build',
    tagline:
      'We learn your brand from you. Let its voice speak through us. Then deliver it back. 32 hours, allocated to what you actually need.',
    price: '$3,500+',
    priceNumber: 3500,
    ctaText: 'Start a Project',
    ctaHref: '/contact',
    highlighted: false,
    icon: 'hammer',
    summary: [
      'Consulting',
      'Branding, voice, and narrative',
      'Scripting and copywriting',
      'Micro-shoot with product',
      'Pre-launch website',
    ],
  },
  {
    id: 'launch',
    name: 'Launch',
    tagline:
      'We bring talent and your product to a location with a camera. We turn a series of shots into a story for your brand (and your customers).',
    price: '$7,000+',
    priceNumber: 7000,
    ctaText: 'Start a Project',
    ctaHref: '/contact',
    highlighted: true,
    icon: 'rocket',
    summary: [
      'Starts with 1 production day',
      'Editing, color, and sound mix',
      'Three revision rounds included',
      'Stills, GIFs, and social ads',
      'Many add-ons available below',
    ],
  },
  {
    id: 'scale',
    name: 'Scale',
    tagline:
      'An ongoing partnership where we continue to support your growth with additional content, creative, and brand consulting.',
    price: 'Contact',
    ctaText: 'Contact Sales',
    ctaHref: '/contact',
    highlighted: false,
    icon: 'trending-up',
    summary: [
      'Brand and marketing strategy',
      'Quarterly ad and asset refreshes',
      'Web design and development',
      'AI workflows and automations',
      'Priority production scheduling',
    ],
  },
];

export const buildAddOns: AddOn[] = [
  {
    id: 'build-branding',
    name: '32 hours of branding, voice, and narrative prep',
    price: 0,
    priceDisplay: 'Included',
    tier: 'build',
    included: true,
  },
  {
    id: 'build-scripting',
    name: 'Scripting and copywriting',
    price: 0,
    priceDisplay: 'Included',
    tier: 'build',
    included: true,
  },
  {
    id: 'build-prelaunch-site',
    name: 'Pre-launch website build-out',
    price: 1500,
    priceDisplay: '$1,500',
    tier: 'build',
    category: 'ADD-ONS',
  },
  {
    id: 'build-half-day-shoot',
    name: 'Half-day shoot (pre-launch assets)',
    price: 2000,
    priceDisplay: '$2,000',
    tier: 'build',
    category: 'ADD-ONS',
  },
];

export const launchAddOns: AddOn[] = [
  // --- Included ---
  {
    id: 'launch-production-days',
    name: 'Production',
    description: 'incl. Director and Cinematographer',
    price: 3000,
    priceDisplay: '$3,000/day',
    tier: 'launch',
    included: true,
    quantity: { min: 1, max: 5, default: 1, unit: 'days' },
  },
  {
    id: 'launch-post-production',
    name: 'Post Production: Editorial, Color Correction, Sound Mix',
    price: 0,
    priceDisplay: 'Included',
    tier: 'launch',
    included: true,
  },
  {
    id: 'launch-stills-social',
    name: '\u21B3 4K stills + social cutdowns',
    description: 'up to 3',
    price: 0,
    priceDisplay: 'Included',
    tier: 'launch',
    included: true,
  },
  {
    id: 'launch-branded-motion',
    name: '\u21B3 Branded motion graphics',
    price: 0,
    priceDisplay: 'Included',
    tier: 'launch',
    included: true,
  },
  // ── CAST + CREW ──
  {
    id: 'launch-talent',
    name: 'Talent',
    price: 1000,
    priceSuffix: '/day',
    priceDisplay: '$1,000/day',
    tier: 'launch',
    category: 'CAST + CREW',
    perDay: true,
    quantity: { min: 1, max: 10, default: 1, unit: 'people' },
  },
  {
    id: 'launch-voiceover',
    name: 'Voiceover Artist',
    price: 500,
    priceSuffix: '/ea',
    priceDisplay: '$500/ea',
    tier: 'launch',
    category: 'CAST + CREW',
    quantity: { min: 1, max: 5, default: 1, unit: 'sessions' },
  },
  {
    id: 'launch-photographer',
    name: 'Photographer',
    price: 2500,
    priceSuffix: '/day',
    priceDisplay: '$2,500/day',
    tier: 'launch',
    category: 'CAST + CREW',
    perDay: true,
    photoSlider: { included: 25, max: 100, extraPrice: 50 },
  },
  {
    id: 'launch-drone',
    name: 'Drone Operator',
    description: 'includes 4K drone and FAA license',
    price: 2500,
    priceSuffix: '/day',
    priceDisplay: '$2,500/day',
    tier: 'launch',
    category: 'CAST + CREW',
    perDay: true,
  },
  {
    id: 'launch-lighting-tech',
    name: 'Lighting Technician',
    price: 1000,
    priceSuffix: '/day',
    priceDisplay: '$1,000/day',
    tier: 'launch',
    category: 'CAST + CREW',
    perDay: true,
  },
  {
    id: 'launch-lighting-assistant',
    name: 'Lighting Assistant',
    price: 750,
    priceSuffix: '/day',
    priceDisplay: '$750/day',
    tier: 'launch',
    category: 'CAST + CREW',
    perDay: true,
  },
  {
    id: 'launch-makeup',
    name: 'Make-up Artist',
    price: 1000,
    priceSuffix: '/day',
    priceDisplay: '$1,000/day',
    tier: 'launch',
    category: 'CAST + CREW',
    perDay: true,
  },
  {
    id: 'launch-pa',
    name: 'Production assistant',
    price: 500,
    priceSuffix: '/day',
    priceDisplay: '$500/day',
    tier: 'launch',
    category: 'CAST + CREW',
    perDay: true,
  },
  // ── RENTALS + TECHNIQUES ──
  {
    id: 'launch-rented-location',
    name: 'Rented Locations',
    price: 0,
    priceSuffix: '/day',
    priceDisplay: '$500+/day',
    tier: 'launch',
    category: 'RENTALS + TECHNIQUES',
    perDay: true,
    slider: { min: 0, max: 3000, step: 250, default: 500 },
    multiSlider: 5,
  },
  {
    id: 'launch-lighting-kit-basic',
    name: 'Basic Lighting Kit',
    price: 500,
    priceSuffix: '/day',
    priceDisplay: '$500/day',
    tier: 'launch',
    category: 'RENTALS + TECHNIQUES',
    perDay: true,
    fundraisingFreebie: true,
  },
  {
    id: 'launch-lighting-kit-premium',
    name: 'Premium Lighting Kit',
    price: 1000,
    priceSuffix: '/day',
    priceDisplay: '$1,000/day',
    tier: 'launch',
    category: 'RENTALS + TECHNIQUES',
    perDay: true,
  },
  {
    id: 'launch-gimbal',
    name: 'Gimbal',
    price: 250,
    priceSuffix: '/day',
    priceDisplay: '$250/day',
    tier: 'launch',
    category: 'RENTALS + TECHNIQUES',
    perDay: true,
  },
  {
    id: 'launch-slider',
    name: 'Slider',
    price: 250,
    priceSuffix: '/day',
    priceDisplay: '$250/day',
    tier: 'launch',
    category: 'RENTALS + TECHNIQUES',
    perDay: true,
  },
  {
    id: 'launch-motion-control',
    name: 'Motion control',
    price: 750,
    priceSuffix: '/day',
    priceDisplay: '$750/day',
    tier: 'launch',
    category: 'RENTALS + TECHNIQUES',
    perDay: true,
  },
  {
    id: 'launch-specialty-rigging',
    name: 'Specialty rigging',
    price: 500,
    priceSuffix: '/day',
    priceDisplay: '$500/day',
    tier: 'launch',
    category: 'RENTALS + TECHNIQUES',
    perDay: true,
  },
  // ── POST PRODUCTION ──
  {
    id: 'launch-additional-social',
    name: 'Additional social edits',
    price: 500,
    priceSuffix: '/ea',
    priceDisplay: '$500/ea',
    tier: 'launch',
    category: 'POST PRODUCTION',
    quantity: { min: 1, max: 10, default: 1, unit: 'edits' },
  },
  {
    id: 'launch-bespoke-motion',
    name: 'Bespoke motion graphics',
    price: 2500,
    priceDisplay: '$2,500+',
    tier: 'launch',
    category: 'POST PRODUCTION',
    slider: { min: 2500, max: 5000, step: 500, default: 2500 },
  },
  {
    id: 'launch-vfx',
    name: 'VFX and renders',
    price: 2500,
    priceDisplay: '$2,500+',
    tier: 'launch',
    category: 'POST PRODUCTION',
    slider: { min: 2500, max: 5000, step: 500, default: 2500 },
  },
];

export const crowdfundingTiers: CrowdfundingTier[] = [
  { discount: 0, percentage: 0, label: 'No crowdfunding discount' },
  { discount: 10, percentage: 2.5, label: '10% off discount for 2.5% of your campaign raise' },
  { discount: 20, percentage: 5, label: '20% off discount for 5% of your campaign raise' },
  { discount: 30, percentage: 10, label: '30% off discount for 10% of your campaign raise' },
];

export const fundraisingPackage: FundraisingPackage = {
  startingPrice: 15000,
  minimumDown: 3000,
  minimumDownPercent: 20,
  paymentTermDays: 180,
  multiplierOnSuccess: 2,
  details: [
    'Pitch video packages starting at $15,000',
    'Minimum 20% down ($3,000)',
    'Rest owed in 180 days, or after you raise — whichever comes first',
    'If you raise within 6 months, unpaid balance owed at 2x (risk coverage)',
  ],
};

// Grey (base includes) + Green (fundraising extras with fundraisingFreebie: true)
export const fundraisingIncluded: AddOn[] = [
  // Grey — base includes
  { id: 'fundraising-scripting', name: 'Scripting and Q&A Support', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true },
  { id: 'fundraising-production-day', name: 'Production: 1 Day (incl. Director and Cinematographer)', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true },
  // Green — sub-items of production
  { id: 'fundraising-one-speaker', name: '\u21B3 One Speaker', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true, fundraisingFreebie: true },
  { id: 'fundraising-teleprompter', name: '\u21B3 Teleprompter', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true, fundraisingFreebie: true },
  { id: 'fundraising-lighting', name: '\u21B3 Interview Lighting Kit', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true, fundraisingFreebie: true },
  // Grey — post production
  { id: 'fundraising-post', name: 'Post Production: Editorial, Color Correction, Sound Mix', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true },
  // Green — sub-items of post
  { id: 'fundraising-branded-motion-graphics', name: '\u21B3 Branded motion graphics', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true, fundraisingFreebie: true },
  { id: 'fundraising-portrait', name: '\u21B3 4K portrait still', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true, fundraisingFreebie: true },
  // Green — website
  { id: 'fundraising-pitch-page', name: 'https://yourCompanyName.Pitch.Page website build-out', price: 0, priceDisplay: 'Included', tier: 'fundraising', included: true, fundraisingFreebie: true },
];

export const fundraisingAddOns: AddOn[] = [
  { id: 'fundraising-broll', name: 'B-roll footage of your product', price: 2500, priceDisplay: '$2,500', tier: 'fundraising' },
  { id: 'fundraising-scripted-videos', name: "Add'l scripted videos (1x)", price: 2500, priceDisplay: '$2,500', tier: 'fundraising' },
  { id: 'fundraising-faqs', name: "Add'l unscripted FAQs (10x)", price: 2500, priceDisplay: '$2,500', tier: 'fundraising' },
  { id: 'fundraising-motion-graphics', name: 'Bespoke motion graphics or renders', price: 2500, priceDisplay: '$2,500', tier: 'fundraising' },
  { id: 'fundraising-rush', name: '72-hour rush fee', price: 2500, priceDisplay: '$2,500', tier: 'fundraising' },
  {
    id: 'fundraising-additional-speakers',
    name: 'Additional speakers',
    price: 2500,
    priceSuffix: '/each',
    priceDisplay: '$2,500/each',
    tier: 'fundraising',
    quantity: { min: 1, max: 10, default: 1, unit: 'speakers' },
  },
  { id: 'fundraising-additional-post', name: 'Additional week of post', price: 2500, priceDisplay: '$2,500', tier: 'fundraising' },
];
